### ISSUE TITLE
Post Limit Error..

### ISSUE THREAD

**Issue by spanjaan** [dimsog/wn-blog-plugin#6]
hello,

when i install the plugin and add post list component in my home page, following error occurred.
How to solve this problem?
please help me.
![Capture](https://user-images.githubusercontent.com/64153858/217207858-a1316cba-e312-4c24-9ab0-3cd49995516b.PNG)

**Comment by willouch** [comment]
Try to change Line 29 in Dimsog\Blog\ComponentsPostList.php:
`$reader = new PostsReader($this->property('limit'));`
By:
`$reader = new PostsReader((int)$this->property('limit'));`
